access: default
edition: 1.0.0
name: inference-pytorch
services:
  ai-project:
    component: fc
    props:
      function:
        caPort: 9000
        codeUri: ./code
        cpu: 2.0
        customContainerConfig:
          image: registry-vpc.cn-shanghai.aliyuncs.com/inference-ns/inference-images:cpu
        description: hello world by serverless devs
        diskSize: 512
        instanceType: e1
        memorySize: 2048
        name: resnet50
        runtime: custom-container
        timeout: 60
      region: ${vars.region}
      service: ${vars.service}
vars:
  region: cn-shanghai
  service:
    logConfig: auto
    name: inference-pytorch-service
