FROM python:latest
WORKDIR /usr/src/app
RUN apt-get update && apt-get install python-dev -y
RUN python3 -m pip install --upgrade pip && \
    pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu && \
    python3 -m pip install --upgrade Pillow && \
    pip install flask && \
    pip install oss2
COPY split/preprocess.py app.py
CMD [ "python", "-u", "/usr/src/app/app.py" ]
