FROM nvcr.io/nvidia/pytorch:22.11-py3
WORKDIR /usr/src/app
RUN python3 -m pip install --upgrade pip && python3 -m pip install --upgrade Pillow && pip install flask
COPY app.py app.py
CMD [ "python3", "-u", "/usr/src/app/app.py" ]
