access: default
edition: 1.0.0
name: inference-pytorch-gpu
services:
  ai-project:
    component: fc
    props:
      function:
        caPort: 9000
        codeUri: ./code
        customContainerConfig:
          image: registry-vpc.cn-shanghai.aliyuncs.com/inference-ns/inference-images:gpu
        description: hello world by serverless devs
        gpuMemorySize: 7168
        instanceType: g1
        memorySize: 16384
        name: resnet50-gpu
        runtime: custom-container
        timeout: 60
      region: ${vars.region}
      service: ${vars.service}
vars:
  region: cn-shanghai
  service:
    logConfig: auto
    name: inference-pytorch-gpu-service
